### ISSUE TITLE
Consider installing MDK and its dependencies

### ISSUE THREAD

**Issue by FMCorz** [danpoltawski/moodle-php-apache#2]
Rather than creating my own Dockerfile for the sake of adding MDK to it, I'm suggesting to add MDK support to this one. The idea is to be able to connect to the container and run MDK commands as a developer typically does.

```
RUN apt-get install -y git
RUN apt-get install -y python-pip
RUN apt-get install python-dev libpq-dev libmysqlclient-dev
RUN pip install moodle-sdk
```

Ideally MDK should already be configured to point to the right folders, binaries, etc...

My ultimate goal is to run older versions of Moodle with older versions of PHP as I have to support them.

**Comment by danpoltawski** [comment]
I am keen to integrate mdk and these docker images very well (and i've been meaning to create an issue in the mdk repo outlining my thoughts for a while now.. maybe after this comment..). However I do not think that doing this is a good approach at all:

Fundamentally it's expected that you mount your Moodle code _into_ these containers, rather than host the code from inside them. Running mdk within these containers is the wrong and has consequences like:

- We'd be tying these containers to mdk versions (or Moodle versions)
- You'd need to put your private ssh keys, tracker credentials and so on into each container
- You are duplicating a big git checkouts, git environemnts and so on
- You have to exec into the container to do stuff
- It's even more violating the good approach of letting each docker container do one thing

For the **long term** solution, let me start the discussion in the mdk issue..

For the **short term**, my approach:

-  I continue to develop with mdk as previously - php70, postgres and apache on my host machine, nothing fancy.
- Then when I need to test in a different environment..
```
# Get the env ready for using with docker instead of mdk temporarily
export MOODLE_DOCKER_WWWROOT=/path/to/mdk/code
mv $MOODLE_DOCKER_WWWROOT/config.php $MOODLE_DOCKER_WWWROOT/config.mdk.php
cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php
export MOODLE_DOCKER_DB=mssql

# Use php56..
cd ~/git/docker-moodle/
git checkout php56

# Start up containers
bin/moodle-docker-compose up -d

# Run behat tests..
bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/init.php
bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --tags=@auth_manual

# Now visit http://127.0.0.1:8000/ to do interruptive testing in browser

# Shut down containers and switch back to mdk-native
bin/moodle-docker-compose down
mv $MOODLE_DOCKER_WWWROOT/config.mdk.php 
 $MOODLE_DOCKER_WWWROOT/config.php
```

Does it make sense?

**Comment by FMCorz** [comment]
Hi Dan,

Yes it does, and I think we agree on mostly everything. My intention was not to switch the development to within the containers, I do strongly agree that PHP code should reside outside of the containers. The main reason why I suggest to shift MDK in there, is for the sole reason of being able to run some MDK commands, which need to know where to get PHP from, mainly.

> We'd be tying these containers to mdk versions (or Moodle versions)

As explained above, this is not my intention.

> You'd need to put your private ssh keys, tracker credentials and so on into each container

Nope, we would only use MDK to run maintenance stuff, such as running CLI scripts, which is heavily dependent on the PHP version.

> You are duplicating a big git checkouts, git environemnts and so on

Nope, we can mount the MDK config folder.

> You have to exec into the container to do stuff

Yes, that's the main block which I haven't found a workaround yet. One approach would be to let MDK determine how to execute a PHP command, for instance by prefiding with `bin/moodle-docker-compose exec webserver`, but then it becomes tricky, when running an MDK command, to determine which container that runs on.

> It's even more violating the good approach of letting each docker container do one thing

As said, I don't want to container to do more, I just want to be able to run the CLI as I'm commonly used to. E.g. an MDK install should look at the container's config (DB setting), and call the right PHP binary.

Does that make sense? (Haven't read the other issue yet)

**Comment by danpoltawski** [comment]
Can you be specific about which mdk commands you want to run on in the container and how you are going to do it? What happens when there is an mdk version mismatch between the container and the host?

**Comment by FMCorz** [comment]
Typically, I'd like to run:

```
mdk purge
mdk install & uninstall
mdk upgrade
mdk run <script>
mdk phpunit
mdk behat (maybe)
```

Really, only the things which are shortcuts to the PHP binary, where Moodle will behave differently on different PHP versions. E.g. testing an install/upgrade on PHP5, vs. PHP7.

**Comment by danpoltawski** [comment]
I'm quite resistant to this because of how it ties with mdk version (I don't want to be thinking about mdk versions in this image) and because it basically seems messy and likely to encourage people to do the _wrong thing_. And if you mount the mdk config folder... what happens with your phpcmd being different on different platforms, it seems problematic. 

What about if I install the mdk dependencies into the image, then you can mount the mdk sripts somewhere and put into path as well as the mdk config if you are going to do that anyway?

**Comment by FMCorz** [comment]
Right, indeed, mounting MDK config is probably a bad idea, some of the settings would need to be container specific, the PHP binary for sure. I have to admit that the cleanest is to be run MDK on the host, and not in the container, I was just looking at an intermediary solution which this issue solves.

**Comment by danpoltawski** [comment]
I'm going to close this issue - we can reopen if there is a seems a compelling reason to do this, but I don't think its right approach here
